- name: add icontrib and non-free repositories
  apt_repository: repo='deb http://httpredir.debian.org/debian jessie main contrib non-free' state=present update_cache=yes

- command: dpkg --configure -a

- name: upgrade system
  apt: upgrade=dist update_cache=yes

- name: install dependencies
  apt: name={{ item }} state=present
  with_items:
    - git
    - ntp
    - vim
    - zsh
    - htop
    - tmux
    - openssl
    - unattended-upgrades
    - apt-listchanges
    - corkscrew
    - python-pip

- name: set hostname
  hostname: name={{hostname | mandatory}}

- name: update hosts file
  lineinfile: >
    dest=/etc/hosts
    regexp='^127\.0\.1\.1'
    line='127.0.1.1 {{ hostname }}'
    owner=root group=root mode=0644

- name: install motd
  template: >
    dest=/etc/motd
    src=motd.j2

- name: activate unattended-upgrades
  copy: src=10periodic dest=/etc/apt/apt.conf.d/10periodic owner=root group=root

- name: configure root bash
  copy: src=bashrc dest=/root/.bashrc

